import './styles.css';
import { diffWordsWithSpace } from 'diff';
import { extractDocument } from './document.js';
import { deterministicScan, moneySetComparison, deterministicComparison } from './deterministic.js';
import { initAnalytics, trackEvent } from './analytics.js';

initAnalytics();
const app = document.querySelector('#app');
const state = { mode:'single', fileA:null, fileB:null, docA:null, docB:null, scanA:null, scanB:null, compare:null, busy:false, error:null, acknowledged:false, activeTab:'overview' };

const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const sev = (v='low') => /high|critical/i.test(v) ? 'high' : /medium/i.test(v) ? 'medium' : 'low';
const money = (n) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);

function uploadBox(slot,label,file){return `<div class="drop"><input data-file="${slot}" type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document"><div><strong>${esc(label)}</strong><small>Drop PDF or Word (.docx) here, or click to browse.</small>${file?`<div class="file-pill">${esc(file.name)}</div>`:''}</div></div>`;}
function finding(item){return `<div class="finding ${sev(item.severity)}"><strong>${esc(item.category||item.title||item.value||'Finding')}</strong>${item.context?`<p>${esc(item.context)}</p>`:''}${item.before?`<p class="diff-before"><b>V1:</b> ${esc(item.before)}</p>`:''}${item.after?`<p class="diff-after"><b>V2:</b> ${esc(item.after)}</p>`:''}${item.impact?`<p><b>Why it matters:</b> ${esc(item.impact)}</p>`:''}<span class="ref">${esc(item.sourceRef||item.sourceRefV1||'')}${item.sourceRefV2?` → ${esc(item.sourceRefV2)}`:''}</span></div>`;}

function safety(){return `<section class="safety-panel"><div class="privacy-banner"><div class="privacy-icon">🔒</div><div><strong>Your documents stay on this device.</strong><p>PDF/DOCX contents are read inside your browser and are not uploaded by this public deploy build.</p></div><span class="privacy-badge">LOCAL-ONLY</span></div><div class="scope-grid"><div class="scope-card does"><h3>What this DOES</h3><ul><li>Reads machine-readable PDF and DOCX files locally.</li><li>Finds money, percentages, deadlines and sensitive fine print.</li><li>Compares V1 ↔ V2 and surfaces material changes.</li><li>Shows source references for verification.</li></ul></div><div class="scope-card does-not"><h3>What this DOES NOT do</h3><ul><li><b>Not legal advice.</b></li><li>Does not guarantee every clause or change will be found.</li><li>Does not OCR image-only PDFs yet.</li><li>Does not store your documents.</li></ul></div></div><label class="ack-row"><input id="acknowledge" type="checkbox" ${state.acknowledged?'checked':''}><span>I understand this is a document-review aid, not legal advice, and I will verify important findings against the original document.</span></label></section>`;}

function overview(){
  if(state.mode==='compare'){
    const s=state.compare?.summary||{};
    const material=state.compare?.material||[];
    return `<div class="section"><div class="dashboard-title"><div><h2>What materially changed?</h2><p>Review the highest-signal local findings first.</p></div><span class="free-badge">LOCAL REVIEW</span></div><div class="material-summary"><div><strong>${s.materialChanges||0}</strong><span>material changes</span></div><div class="danger"><strong>${s.highMaterialChanges||0}</strong><span>high priority</span></div><div><strong>${s.pairedFinancialChanges||0}</strong><span>financial changes</span></div><div><strong>${s.sensitiveTopicChanges||0}</strong><span>sensitive-topic changes</span></div></div>${material.slice(0,20).map(finding).join('')||'<p class="empty">No material changes detected.</p>'}</div>`;
  }
  return `<div class="section"><div class="notice info"><b>Local document scan completed.</b> Review these findings against the original.</div><div class="summary-strip"><div><strong>${state.scanA?.money?.length||0}</strong><span>money references</span></div><div><strong>${state.scanA?.deadlines?.length||0}</strong><span>deadline hits</span></div><div><strong>${state.scanA?.watchTerms?.length||0}</strong><span>fine-print watch hits</span></div></div>${(state.scanA?.watchTerms||[]).slice(0,15).map(finding).join('')||'<p class="empty">No watch terms detected.</p>'}</div>`;
}
function moneyTab(){
  if(state.mode==='compare') return `<div class="section"><h3>Financial changes</h3>${(state.compare?.financial||[]).map(x=>finding({title:x.label,before:x.beforeValue,after:x.afterValue,impact:x.kind==='money'?`${x.delta>=0?'Increase':'Decrease'} of ${money(Math.abs(x.delta))}`:`${x.delta>=0?'Increase':'Decrease'} of ${Math.abs(x.delta)} percentage points`,sourceRefV1:x.sourceRefV1,sourceRefV2:x.sourceRefV2,severity:Math.abs(x.delta)>=50000?'high':'medium'})).join('')||'<p class="empty">No paired financial changes detected.</p>'}<h3>Amounts only in one version</h3>${renderMoneyDelta()}</div>`;
  return `<div class="section"><h3>Detected money references</h3>${state.scanA?.money?.length?`<div class="table-wrap"><table><thead><tr><th>Amount</th><th>Source</th><th>Context</th></tr></thead><tbody>${state.scanA.money.map(x=>`<tr><td class="money">${esc(x.value)}</td><td><span class="ref">${esc(x.sourceRef)}</span></td><td>${esc(x.context)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="empty">No dollar amounts detected.</p>'}</div>`;
}
function fineTab(){const rows=state.mode==='compare'?(state.compare?.sensitive||[]):(state.scanA?.watchTerms||[]); return `<div class="section"><h3>${state.mode==='compare'?'Fine-print changes':'Fine-print watch'}</h3>${rows.map(finding).join('')||'<p class="empty">No fine-print findings detected.</p>'}</div>`;}
function changesTab(){if(!state.docA||!state.docB)return ''; const a=state.docA.sections.map(s=>s.text).join('\n'),b=state.docB.sections.map(s=>s.text).join('\n'); const diff=diffWordsWithSpace(a,b).slice(0,1200); return `<div class="section"><h3>Word-for-word diff</h3><div class="finding raw-diff">${diff.map(p=>p.added?`<span class="diff-after">${esc(p.value)}</span>`:p.removed?`<span class="diff-before">${esc(p.value)}</span>`:esc(p.value)).join('')}</div></div>`;}
function sourceTab(){return `<div class="section">${[state.docA,state.docB].filter(Boolean).map((d,i)=>`<h3>${state.mode==='compare'?`Version ${i+1}: `:''}${esc(d.name)}</h3><div class="finding source-box">${d.sections.slice(0,250).map(s=>`<b>[${esc(s.ref)}]</b> ${esc(s.text)}`).join('\n\n')}</div>`).join('')}</div>`;}
function renderMoneyDelta(){const d=moneySetComparison(state.scanA,state.scanB); const rows=[...d.removed.map(x=>({side:'Only in V1',...x})),...d.added.map(x=>({side:'Only in V2',...x}))]; return rows.length?`<div class="table-wrap"><table><tbody>${rows.map(r=>`<tr><td>${r.side}</td><td class="money">${money(r.amount)}</td><td>${esc(r.examples[0]?.context||'')}</td></tr>`).join('')}</tbody></table></div>`:'<p class="empty">No unique dollar amounts detected.</p>';}
function results(){if(!state.scanA)return ''; const tabs=state.mode==='compare'?['overview','money','fineprint','changes','source']:['overview','money','fineprint','source']; let body=state.activeTab==='overview'?overview():state.activeTab==='money'?moneyTab():state.activeTab==='fineprint'?fineTab():state.activeTab==='changes'?changesTab():sourceTab(); return `<div class="results"><div class="card"><div class="result-head"><div><h2>${state.mode==='compare'?'Revision Audit':'Document Audit'}</h2><div class="status">${esc(state.docA?.name||'')}${state.docB?` compared with ${esc(state.docB.name)}`:''}</div></div></div></div><div class="card"><div class="tabs">${tabs.map(t=>`<button class="tab ${state.activeTab===t?'active':''}" data-tab="${t}">${t==='fineprint'?'Fine Print':t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div>${body}</div></div>`;}

function render(){const can=state.fileA&&(state.mode==='single'||state.fileB)&&state.acknowledged&&!state.busy; app.innerHTML=`<main class="shell"><div class="brandline"><div class="brandmark">TB</div>Tammy Builds AI + Automation<span class="version-badge">PRIVATE BETA · v0.1.6</span></div><section class="hero"><div class="hero-topline"><span class="hero-version">Private Beta v0.1.6</span><span class="hero-local">🔒 Local-only document processing</span></div><h1>Contract & Budget Inspector</h1><p>Review dense film, production and legal documents. Scan money, percentages, deadlines and fine print — or compare two versions and surface material changes with source references.</p><div class="badges"><span class="badge">PDF + DOCX</span><span class="badge">Money scan</span><span class="badge">Fine-print watch</span><span class="badge">V1 ↔ V2 comparison</span><span class="badge">No document upload</span></div></section>${safety()}<section class="card no-print"><div class="modebar"><button class="mode ${state.mode==='single'?'active':''}" data-mode="single">Analyze one document</button><button class="mode ${state.mode==='compare'?'active':''}" data-mode="compare">Compare two versions</button></div><div class="upload-grid ${state.mode==='single'?'single':''}">${uploadBox('A',state.mode==='compare'?'Version 1 / Original':'Contract, budget or production document',state.fileA)}${state.mode==='compare'?uploadBox('B','Version 2 / Revised',state.fileB):''}</div>${state.error?`<div class="notice warn"><b>Problem:</b> ${esc(state.error)}</div>`:''}<div class="actions"><button class="primary" id="analyze" ${can?'':'disabled'}>${state.busy?'Reviewing locally…':state.mode==='compare'?'Compare Locally':'Audit Locally'}</button>${state.scanA?'<button class="secondary" id="print">Print / Save Report</button><button class="secondary" id="export">Export JSON</button>':''}<span class="status">Not legal advice · Verify material findings against the original.</span></div></section>${results()}<footer class="app-footer"><strong>Contract & Budget Inspector · Private Beta v0.1.6</strong><span>Local-only processing · No document upload · Not legal advice</span></footer></main>`; bind();}
function bind(){document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;state.fileA=null;state.fileB=null;state.docA=null;state.docB=null;state.scanA=null;state.scanB=null;state.compare=null;state.activeTab='overview';render();}); document.querySelectorAll('[data-file]').forEach(i=>i.onchange=()=>{state[`file${i.dataset.file}`]=i.files?.[0]||null;state.scanA=null;state.scanB=null;state.compare=null;render();}); document.querySelector('#acknowledge')?.addEventListener('change',e=>{state.acknowledged=e.target.checked;render();}); document.querySelector('#analyze')?.addEventListener('click',analyze); document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.activeTab=b.dataset.tab;render();}); document.querySelector('#print')?.addEventListener('click',()=>{trackEvent('report_printed',{mode:state.mode});window.print();}); document.querySelector('#export')?.addEventListener('click',exportJson);}
async function analyze(){trackEvent('analysis_started',{mode:state.mode});state.busy=true;state.error=null;render(); try{state.docA=await extractDocument(state.fileA);state.scanA=deterministicScan(state.docA);if(state.mode==='compare'){state.docB=await extractDocument(state.fileB);state.scanB=deterministicScan(state.docB);state.compare=deterministicComparison(state.docA,state.docB,state.scanA,state.scanB);}trackEvent('analysis_completed',{mode:state.mode,scan_warning:Boolean(state.docA?.scanWarning||state.docB?.scanWarning)});}catch(err){state.error=err?.message||String(err);trackEvent('analysis_failed',{mode:state.mode});}state.busy=false;render();}
function exportJson(){const data={generatedAt:new Date().toISOString(),mode:state.mode,documents:[state.docA?.name,state.docB?.name].filter(Boolean),deterministic:{a:state.scanA,b:state.scanB,comparison:state.compare}}; const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url;a.download=`contract-budget-inspector-${Date.now()}.json`;a.click();URL.revokeObjectURL(url);trackEvent('json_exported',{mode:state.mode});}
render();
